######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2023, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("tree_buscos.png",sep="/") 
my_width <- 35
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.55

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Alectoris_rufa', 'Alectoris_rufa', 'Alectoris_rufa', 'Alectoris_rufa', 'Anolis', 'Anolis', 'Anolis', 'Anolis', 'Centrocercus_urophasianus', 'Centrocercus_urophasianus', 'Centrocercus_urophasianus', 'Centrocercus_urophasianus', 'Chicken', 'Chicken', 'Chicken', 'Chicken', 'Coturnix_japonica', 'Coturnix_japonica', 'Coturnix_japonica', 'Coturnix_japonica', 'Falco_cherrug', 'Falco_cherrug', 'Falco_cherrug', 'Falco_cherrug', 'Lagopus_muta', 'Lagopus_muta', 'Lagopus_muta', 'Lagopus_muta', 'Mallard', 'Mallard', 'Mallard', 'Mallard', 'Melegris_gallopavo', 'Melegris_gallopavo', 'Melegris_gallopavo', 'Melegris_gallopavo', 'Numida_meleagris', 'Numida_meleagris', 'Numida_meleagris', 'Numida_meleagris', 'Phasianus_colchicus', 'Phasianus_colchicus', 'Phasianus_colchicus', 'Phasianus_colchicus', 'Tympanuchus_pallidicinctus', 'Tympanuchus_pallidicinctus', 'Tympanuchus_pallidicinctus', 'Tympanuchus_pallidicinctus')
my_species <- factor(my_species)
#my_species <- factor(my_species, levels = c("Tympanuchus_pallidicinctus", "Centrocercus_urophasianus", "Lagopus_muta", "Melegris_gallopavo", "Phasianus_colchicus", "Chicken", "Coturnix_japonica", "Alectoris_rufa", "Numida_meleagris", "Mallard", "Falco_cherrug", "Anolis"))

my_species <- factor(my_species, levels = c("Anolis", "Falco_cherrug", "Mallard", "Numida_meleagris", "Alectoris_rufa", "Coturnix_japonica", "Chicken", "Phasianus_colchicus", "Melegris_gallopavo", "Lagopus_muta", "Centrocercus_urophasianus", "Tympanuchus_pallidicinctus"))
# reorder your species here just by changing the values in the vector :
my_percentage <- c(96.6, 0.3, 0.5, 2.6, 78.2, 1.4, 3.0, 17.4, 95.6, 0.3, 0.8, 3.3, 96.2, 0.3, 0.8, 2.7, 96.2, 0.2, 0.7, 2.9, 96.7, 0.1, 0.8, 2.4, 96.4, 0.3, 0.5, 2.8, 95.9, 0.6, 0.8, 2.7, 89.9, 0.2, 5.1, 4.8, 96.6, 0.2, 0.6, 2.6, 96.6, 0.2, 0.6, 2.6, 96.1, 0.3, 0.6, 3.0)
my_values <- c(8051, 21, 39, 227, 6524, 117, 252, 1445, 7968, 24, 70, 276, 8020, 28, 65, 225, 8019, 18, 61, 240, 8067, 12, 63, 196, 8041, 23, 45, 229, 7999, 52, 65, 222, 7492, 19, 428, 399, 8053, 16, 53, 216, 8053, 13, 47, 225, 8014, 24, 46, 254)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 10) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n% BUSCOs (aves_odb=8338)") + 
  
  theme(plot.title = element_text(family=my_family, hjust=5, colour = "black", size = rel(10)*my_size_ratio, face = "bold"),
        legend.title=element_text(size=22),
        legend.key = element_rect(fill = "transparent", colour = "transparent"),
        panel.background=element_rect(fill="transparent",colour=NA),
        plot.background=element_rect(fill="transparent",colour=NA),
        legend.background = element_rect(fill = "transparent")) +
  
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) +
  theme(panel.background = element_rect()) +
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  #theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(0.80, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.1, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend())

for(i in rev(c(1:length(levels(my_species))))){
  detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
  total_buscos <- sum(detailed_values)
  figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
}

figure
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)

print("Done")
